### ISSUE TITLE
Installer doesn't find it's own files on wine, Linux.

### ISSUE THREAD

**Issue by Baerbeisser** [BFrizzleFoShizzle/RE_Kenshi#8]
Kenshi: 1.0.68 GOG
RE_Kenshi: 0.2.14
winetricks: corefonts ogg physx vcrun2022 dotnet48

![re_kenshi-installer-bug](https://github.com/user-attachments/assets/ab6d995d-b359-4825-a7a7-e6fb4cc2b917)

Looks like it doesn't find it's own root path?
Game runs btw, with lots of mods. But it has kinda the same issue; the start script has to cd in the games folder or it crashes during loading of the world.

edit: yes, cd'ing to the re_kenshi folder helped. Still not nice tho.

**Comment by BFrizzleFoShizzle** [comment]
Thanks for the detailed report.

Looks like an issue with my code using the CWD instead of the executable path to find the install resources.  
Up until now, I assumed fixing the installer on Linux would be a pain in the ass to fix, but if this is the only issue stopping it from working, it should be quick and easy to fix.

I've planned on rewriting the installer to self-package everything into a single binary as most of the installer error reports I get are from missing installer files (most likely due to people not extracting everything in the installer archive), and combining all the data into a self-extracting installer might also solve your problem.

If I don't get around to doing the self-packaging thing, I should at least be able to use the installer base path as the file search path instead of (or on top of) the CWD in the next release.

**Comment by BFrizzleFoShizzle** [comment]
I just tested the new self-packaged installer on Mint, and it works fine under Wine, so this should be solved in the next release.
(you can currently find a prerelease build of the new installer on the GMG discord if you want to test)

**Comment by BFrizzleFoShizzle** [comment]
This should be fixed in the latest release. Let me know if there's issues.
